version: 2.1
executors:
  my-executor:
    docker:
      - image: cimg/openjdk:11.0

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
        command: '-X verify'
        executor: my-executor
